destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/3dfier-pdf"
port: 4010
output: pdf
product: 3dfier
print_title: 3dfier documentation
print_subtitle: version 1.2.2
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: 3dfier_sidebar
